# Generated by Django 6.0.8 on 2026-08-29 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_user_is_update_user_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_update',
            new_name='is_updated',
        ),
    ]
